baseURL = "/"
languageCode = "en-us"
title = "Tetelestai | Delivering change"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Tetelestai"

  [params.homepage_meta_tags]
    meta_description = "."
    meta_og_title = "Tetelestai"
    meta_og_type = "website"
    meta_og_url = "."
    meta_og_image = "."
    meta_og_description = "."

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
	  name = "Services"
	  url = "/services/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
